Update Ros2ControlSystem.cpp: correct joint.acceleration
cyberbotics/webots_ros2 pull request #1023
Opened 2024-12-27 12:57 UTC by onionsflying

**Description**
I noticed that the sign of the acceleration was reversed.

2024-12-29 23:23 UTC, lukicdarkoo approved these changes
Looks good, thank you!

2024-12-29 23:31 UTC, lukicdarkoo requested changes
Can you please also make an entry in the changelog?

2024-12-29 23:58 UTC, onionsflying commented
Sure, I updated the changelog.

2025-01-02 23:28 UTC, lukicdarkoo approved these changes
Thank you

2025-01-14 03:21 UTC, onionsflying commented
@lukicdarkoo Hi, could this PR be merged?

2025-01-14 09:52 UTC, lukicdarkoo commented
@onionsflying I will merge for you as some of the CI tests are failing (not related to your changes). Thank you!

2025-01-14 09:52 UTC, merged