Range and qos
cyberbotics/webots_ros2 pull request #198
Opened 2021-02-01 12:40 UTC by fmrico

**Description**
This PR contains:
* support for RangeFinder
* Fix camera_info content and publication rate
* Fix QoS

**Affected Packages**
List of affected packages:
  - webots_ros2_core

2021-02-01 16:14 UTC, lukicdarkoo requested changes
Thank you very much for this nice contribution!

I did a few minor fixes to make the CI pass.

Before the merge, can you tell me why did you change `wheel_radius` in `tiago.yaml`?

2021-02-01 16:31 UTC, fmrico commented on webots_ros2_tiago/resource/tiago.yaml
> +    wheel_radius: 1
Hi Lukic, I will push now the values I used.

2021-02-01 16:33 UTC, fmrico commented
Hi @lukicdarkoo 

I modified the `wheel_distance` and `wheel_radius` to approximate reasonable values because the original values made the odometry updates fail. I got to map a complex environment with these values.

Best

2021-02-01 16:47 UTC, lukicdarkoo commented
> Hi @lukicdarkoo
> 
> I modified the `wheel_distance` and `wheel_radius` to approximate reasonable values because the original values produced erroneous updates of the `odom`->`base_link` transform. I got to map a complex environment with these values.
> 
> Best

In that case, the problem is in `webots_differential_drive_node.py`. I will check what is happening. It works fine for TurtleBot and e-puck.

2021-02-02 09:17 UTC, lukicdarkoo approved these changes
Looks good, thank you. Feel free to merge it.

P.S. I see that the odometry parameters slightly deviated from the original values. Good to know that these values work better.

2021-02-02 15:50 UTC, fmrico commented
Hi @lukicdarkoo 

I think that I have no permissions to merge it. Could you merge it for me, please?

Thanks for your help ;)

2021-02-02 15:52 UTC, omichel commented
@fmrico: I just added you in the committers group, so that you should be able to accept my invitation and merge this PR (and others).

2021-02-02 15:55 UTC, merged

2021-02-02 15:55 UTC, fmrico commented
Thanks, @omichel  ;)