Add drone (Mavic) example
cyberbotics/webots_ros2 pull request #204
Opened 2021-02-19 15:23 UTC by lukicdarkoo

This adds a simple world, drone, and controller example based on the Mavic world:
https://www.cyberbotics.com/doc/guide/mavic-2-pro?version=develop

2021-02-21 12:50 UTC, lukicdarkoo commented
Retry DeepCode

2021-02-22 09:06 UTC, omichel requested changes
Very nice.

2021-02-22 09:06 UTC, omichel commented on webots_ros2_mavic/worlds/mavic_world.wbt
> +  rotation 9.38185669e-07 0 0.99999999999956 3.141590777218456
```suggestion
  rotation 0 0 1 3.141590777218456
```

2021-02-22 09:49 UTC, omichel approved these changes

2021-02-22 11:12 UTC, merged