Cleanup delete unnecessary packages
cyberbotics/webots_ros2 pull request #301
Opened 2021-09-22 07:36 UTC by lukicdarkoo

Resolves #239

Deleted packages:
- webots_ros2_examples
- webots_ros2_tiago
- webots_ros2_tutorials

@stefaniapedrazzi, instead of deleting the `webots_ros2_tiago` package maybe we can replace it with the one we developed for OpenDR (but without the face recognition).

2021-09-28 14:06 UTC, BenjaminHug8 requested changes
It works nicely on my side!

Beside waiting for the new CI to finished and my question for the `webots_ros2/package.xml`, I just have some warnings most probably due to the deletion of packages that I think we can resolve:
`[0.392s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/benjamin/ros2_ws/install/webots_ros2_ur_e_description' in the environment variable AMENT_PREFIX_PATH doesn't exist

[0.392s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/benjamin/ros2_ws/install/webots_ros2_demos' in the environment variable AMENT_PREFIX_PATH doesn't exist

[0.392s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/benjamin/ros2_ws/install/webots_ros2_tutorials' in the environment variable AMENT_PREFIX_PATH doesn't exist

[0.392s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/benjamin/ros2_ws/install/webots_ros2_examples' in the environment variable AMENT_PREFIX_PATH doesn't exist

[0.392s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/benjamin/ros2_ws/install/webots_ros2_abb' in the environment variable AMENT_PREFIX_PATH doesn't exist
`

2021-09-28 14:24 UTC, lukicdarkoo commented on webots_ros2/package.xml
> -  <exec_depend>webots_ros2_tiago</exec_depend>
Yes, you right

2021-09-28 14:27 UTC, lukicdarkoo commented
> I just have some warnings most probably due to the deletion of packages that I think we can resolve

`rm -rf build install log` and building the workspace in a new terminal should make the warnings disappear.

2021-10-01 08:47 UTC, BenjaminHug8 approved these changes
Perfect, thank you !

2021-10-01 12:13 UTC, merged