Conversion enu/flu of worlds and controller
cyberbotics/webots_ros2 pull request #316
Opened 2021-11-02 13:22 UTC by BenjaminHug8

**Description**
This PR is to convert world and controller of `webots_ros2` to match flu/enu conversion R2022a.

2021-11-02 13:24 UTC, BenjaminHug8 commented
I noticed that some worlds that were deleted on `master` were not deleted in `develop`, so I cleaned it and deleted some worlds for `tiago` and `universal_robot`.

2021-11-10 10:37 UTC, BenjaminHug8 commented
@omichel is there anyway to tell the CI to use the branch `feature-enu-plan` ?

2021-11-10 11:17 UTC, omichel commented
This is not easy as the CI is installing a debian package, see https://github.com/cyberbotics/webots_ros2/blob/master/scripts/ci_after_init.bash
So if you want the CI to use a build from the feature-enu-plan branch, you should create a deb package of this branch and use it.
This is probably not worth. We should simply test locally and ignore the CI tests for this PR (we may change the setting to allow us to merge it).

2021-11-10 11:34 UTC, BenjaminHug8 commented
> This is not easy as the CI is installing a debian package, see https://github.com/cyberbotics/webots_ros2/blob/master/scripts/ci_after_init.bash So if you want the CI to use a build from the feature-enu-plan branch, you should create a deb package of this branch and use it. This is probably not worth. We should simply test locally and ignore the CI tests for this PR (we may change the setting to allow us to merge it).

Ok I thought it would not be that easy to do it, thank you for the information.

2021-11-15 13:34 UTC, joachimhgg requested changes
Just small details. 
- clean the rotation of the worlds
- orientation of the door is wrong in turtlebot3
- universal_robot.wbt: box not FLU
- need to update doc ? https://github.com/cyberbotics/webots_ros2/wiki/Examples

2021-11-19 10:24 UTC, BenjaminHug8 commented
>     * orientation of the door is wrong in turtlebot3
I did it intentionally because otherwise the robot might (half) fall.

![Screenshot from 2021-11-19 11-18-50](https://user-images.githubusercontent.com/61198898/142606566-981e7d4d-ef59-417a-9ef6-7519df4f3031.png)

>     * need to update doc ? https://github.com/cyberbotics/webots_ros2/wiki/Examples

I have to check if FLU has an impact on the doc but the structure of the sub-packages of `webots_ros2` has changed so a refresh will be great in any case :+1: .

2021-11-22 07:34 UTC, BenjaminHug8 commented
Documentation has been updated.

2021-11-22 09:32 UTC, joachimhgg requested changes
Thanks! Last things to change, the walls of `rats_life_benchmark.wbt` are not FLU.

2021-11-22 16:02 UTC, BenjaminHug8 commented on webots_ros2_epuck/worlds/epuck_world.wbt
> +  follow "e-puck-old"
As `followType` has never been defined, `follow` has no effect and the ViewPoint will never move.
Thus I will remove `follow "e-puck-old"`.

2021-11-29 10:02 UTC, joachimhgg approved these changes
Thanks!

2021-12-16 14:00 UTC, lukicdarkoo commented
Before release:
- Fix CI for the develop branch (https://github.com/cyberbotics/webots_ros2/blob/4e7802349be45d5484475b00eea84a740a441756/scripts/ci_before_init_embed.bash#L3)
- Make sure all tests are passing on the develop branch (not critical, but good to have)
- We should merge this into the develop branch
- Merge `master` into `develop`

Tomorrow:
- Merge develop to master

2021-12-17 11:25 UTC, lukicdarkoo commented on scripts/ci_after_init.bash
> +fi
```suggestion
fi

```
We don't need this diff

2021-12-17 11:25 UTC, lukicdarkoo submitted a review, later dismissed
Thank you

2021-12-17 11:32 UTC, BenjaminHug8 commented
I will just wait to merge the [gps PR](https://github.com/cyberbotics/webots_ros2/pull/354/) before merging this one into develop (the gps PR should be ready after CI tests).

2021-12-17 15:44 UTC, lukicdarkoo approved these changes
Thank you

2021-12-17 15:48 UTC, merged