Moveit dependency is failing
cyberbotics/webots_ros2 pull request #373
Opened 2022-01-14 09:45 UTC by BenjaminHug8

**Description**
Resolve the `moveit` dependency.

2022-01-14 10:21 UTC, BenjaminHug8 commented
Waiting on [this issue](https://github.com/ros-planning/moveit2/issues/990).

2022-01-18 11:36 UTC, lukicdarkoo commented
Long term, maybe it is better for MoveIt (as well other integrations) to be an optional dependency, or to stress using `webots_ros2_driver` (instead of `webots_ros2`), or to separate `webots_ros2` core packages from examples.

2022-01-18 15:36 UTC, omichel requested changes

2022-01-18 15:36 UTC, omichel commented on scripts/ci_after_init.bash
> +apt-cache policy
```suggestion
apt-cache policy

```

2022-01-18 15:36 UTC, omichel commented on webots_ros2_universal_robot/launch/moveit_demo_launch.py
> +                                                please install it in order to use this demo.'))
```suggestion
                                                please install it in order to run this demo.'))
```

2022-01-18 15:36 UTC, omichel commented on webots_ros2_universal_robot/launch/moveit_demo_launch.py
> +    # Check if nav2_bringup is installed
Shouldn't it be moveit here?
```suggestion
    # Check if moveit is installed
```

2022-01-18 16:22 UTC, omichel requested changes

2022-01-18 16:22 UTC, omichel commented on scripts/ci_after_init.bash
> +fi
This file is simply missing a carriage return at the end.

2022-01-18 16:25 UTC, omichel approved these changes
Thank you.

2022-01-19 07:14 UTC, merged