Enhancement convert windows support to wsl
cyberbotics/webots_ros2 pull request #481
Opened 2022-10-11 07:59 UTC by ygoumaz

Currently, the documentation and tutorials detail how to use `webots_ros2` on Windows and the package officially supports installation on this platform. However, using ROS2 outside of a Linux environment is not trivial and many other distributed packages are not maintained for macOS or Windows.

This PR deprecates the compatibility with Windows, but adds the possibility to run the package in WSL (Windows Subsystem for Linux). This way Webots still runs on Windows, while the whole ROS2 part can be run in a Linux environment, which greatly increases the simplicity of package maintenance, usage and the possibility to use other distributed packages. In short, the experience of Windows users is greatly improved and simplified.

In addition, this PR changes the way Webots is searched in the system at launch. The order of priority is as follows:
- Installation contained in ROS2_WEBOTS_HOME, regardless of version.
- Installation contained in WEBOTS_HOME, regardless of version.
- Search in the default installation folders (compatible version only):
  - `C:\Program Files\Webots` on the WSL system
  - `/usr/local/webots` and `/snap/webots/current/usr/share/webots` on Linux
  - `/Applications/Webots.app` on macOS
- Suggest an automatic installation of the compatible version of Webots in `~/.ros/webots`.

2022-10-13 16:08 UTC, omichel requested changes
It looks good to me (although I didn't test it yet).

2022-10-13 16:08 UTC, omichel commented on webots_ros2_driver/webots_ros2_driver/urdf_spawner.py
> +            relative_path_prefix = subprocess.check_output(['wslpath', '-w', relative_path_prefix]).strip().decode("utf-8").replace('\\', '/')
```suggestion
            relative_path_prefix = subprocess.check_output(['wslpath', '-w', relative_path_prefix]).strip().decode('utf-8').replace('\\', '/')
```

2022-10-13 16:08 UTC, omichel commented on webots_ros2_mavic/launch/robot_launch.py
> +        controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/'
```suggestion
    controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/' if is_wsl() else ''
```

2022-10-13 16:08 UTC, omichel commented on webots_ros2_epuck/launch/robot_launch.py
> +        controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/'
```suggestion
    controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/' if is_wsl() else ''
```

2022-10-13 16:08 UTC, omichel commented on webots_ros2_driver/webots_ros2_driver/webots_launcher.py
> +            controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/'
```suggestion
        controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/' if is_wsl() else ''
```

2022-10-13 16:08 UTC, omichel commented on webots_ros2_tesla/launch/robot_launch.py
> +        controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/'
```suggestion
    controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/' if is_wsl() else ''
```

2022-10-13 16:08 UTC, omichel commented on webots_ros2_tests/test/test_system_driver.py
> +        controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/'
```suggestion
    controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/' if is_wsl() else ''
```

2022-10-13 16:08 UTC, omichel commented on webots_ros2_tiago/launch/robot_launch.py
> +        controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/'
```suggestion
    controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/' if is_wsl() else ''
```

2022-10-13 16:08 UTC, omichel commented on webots_ros2_turtlebot/launch/robot_launch.py
> +        controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/'
Same comment here.

2022-10-13 16:08 UTC, omichel commented on webots_ros2_universal_robot/launch/multirobot_launch.py
> +        controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/'
Same comment here.

2022-10-13 16:08 UTC, omichel commented on webots_ros2_universal_robot/launch/robot_launch/robot_nodes_launch.py
> +        controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/'
```suggestion
    controller_url = 'tcp://' + get_wsl_ip_address() + ':1234/' if is_wsl() else ''
```

2022-10-14 07:27 UTC, omichel approved these changes
Thank you.
As discussed, the wiki page should be improved.

2022-10-14 10:01 UTC, ygoumaz commented
I updated the 2 following pages:
- https://github.com/cyberbotics/webots_ros2/wiki/Getting-Started
- https://github.com/cyberbotics/webots_ros2/wiki/Complete-Installation-Guide

Let me know if this is ok for you.

2022-10-17 09:20 UTC, omichel commented
As discussed, we should remove the macOS instructions from the wiki as we won't support macOS directly, but only through docker.

2022-10-17 13:20 UTC, ygoumaz commented
The documentation about macOS is removed for now, until the docker solution is ready.

2022-10-17 13:20 UTC, merged