Fix urdf spawner with urdf path
cyberbotics/webots_ros2 pull request #610
Opened 2023-01-31 17:19 UTC by ygoumaz

Fixes #558 and #581.

## **#581** ##

URDFs can be spawned in 2 different ways:
- By giving the complete robot description and the relative path to the resources.
- By giving only the path to the URDF file.

The first way was correctly handled on WSL and macOS. The second one is trickier, as the path must be kept to open the file in the Linux part, while the URL should be edited, as it is then used in the Webots instance, respectively on Windows and macOS.

To counter this problem, on Windows and macOS, the URDF file is opened by the `ROS2_supervisor` and is passed as the robot description, and the relative path is set according to the URDF path by searching for the 'share' directory.

The URL edition is now completely done in the supervisor, for clarity.

## **#558** ##

The URLs of xacro files in the universal robot example are reverted to the correct RVIZ format. To fix the issue on macOS, the resource folder is now copied inside another folder that has the same name as the package.

2023-02-01 15:43 UTC, ad-daniel requested changes
Looks good to me, thank you.
@PymZoR may I ask you to check if the proposed patch fixes your issue?

2023-02-01 15:43 UTC, ad-daniel commented on webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py
> +                    sys.exit('Input file "%s" does not exists.' % robot.urdf_path)
```suggestion
                    sys.exit('Input file "%s" does not exist.' % robot.urdf_path)
```

2023-02-01 15:43 UTC, ad-daniel commented on webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py
> +                    sys.exit('"%s" is not a URDF file.' % robot.urdf_path)
```suggestion
                    sys.exit('"%s" is not an URDF file.' % robot.urdf_path)
```

2023-02-01 15:43 UTC, ad-daniel commented on webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py
> +                    sys.exit('Could not read the URDF file.')
this should probably be indented

2023-02-02 15:41 UTC, PymZoR commented
@ad-daniel I'm going to check it this week-end

2023-02-06 11:56 UTC, ygoumaz commented
I will merge this PR, so that we can move on with the release of version 2023.0.2.

@PymZoR feel free to mention if the fix doesn't work for you.

2023-02-07 07:22 UTC, ad-daniel approved these changes
Looks good to me

2023-02-07 07:56 UTC, merged