Adding port parameter and usage of webots world project file to launcher.py
cyberbotics/webots_ros2 pull request #639
Opened 2023-02-23 08:18 UTC by sebastianohl

**Description**
The webots driver launcher do not offer the possibility to set the streaming port. this prevents the use in multi user environments where every user wants to see its own simulation.
Moreover, the launcher only copies the world file and ignores the world project file. Therefore, custom settings (e.g. optional renderings are ignored).

This pull request adds a parameter to webots launcher constructor to set the port. The default parameter setting is set to the default port 1234. Therefore, there should not be any difference for existing setups.
Moreover, the copy of the world project file is added. The execute()-Function searches if a .wbproj file with the same name as the world file exists and then copies it to the location of the temporary world file. When webots starts, it uses the world project file.

**Related Issues**

**Affected Packages**
  - webots_ros2_driver

**Tasks**

2023-02-23 10:49 UTC, ygoumaz requested changes
Very nice contribution, thanks a lot! I have some minor suggestions on the code. Also, two additional steps should be added:

- On macOS, resources should be copied to the shared folder. The wbproj should also be copied so that macOS users also benefit from the feature. This can be added here along with the world file: https://github.com/cyberbotics/webots_ros2/blob/801c73c7c4e24361f73f2c532542f75aadcc5340/webots_ros2_driver/webots_ros2_driver/webots_launcher.py#L213
- We now are able to choose the port of Webots but we should also be able to easier choose the target port of started controllers/nodes. Based on how we setup the target in the examples of the packages, the `controller_url_prefix()` function should be enhanced with an additional `port` parameter. The default value should be 1234 as well if no port is given. https://github.com/cyberbotics/webots_ros2/blob/801c73c7c4e24361f73f2c532542f75aadcc5340/webots_ros2_driver/webots_ros2_driver/utils.py#L138

2023-02-23 10:49 UTC, ygoumaz commented on webots_ros2_driver/webots_ros2_driver/webots_launcher.py
> +        wbproj_path = wbproj_path.with_name("."+wbproj_path.name)
```suggestion
        wbproj_path = Path(world_path).with_name('.' + Path(world_path).stem + '.wbproj')
```

2023-02-23 10:49 UTC, ygoumaz commented on webots_ros2_driver/webots_ros2_driver/webots_launcher.py
> +            wbproj_copy_path = wbproj_copy_path.with_name("."+wbproj_copy_path.name)
```suggestion
            wbproj_copy_path = Path(self.__world_copy.name).with_name('.' + Path(self.__world_copy.name).stem + '.wbproj')
```

2023-02-23 12:10 UTC, sebastianohl commented on webots_ros2_driver/webots_ros2_driver/webots_launcher.py
> +        wbproj_path = wbproj_path.with_name("."+wbproj_path.name)
I added the changed in the new commit

2023-02-23 12:10 UTC, sebastianohl commented on webots_ros2_driver/webots_ros2_driver/webots_launcher.py
> +            wbproj_copy_path = wbproj_copy_path.with_name("."+wbproj_copy_path.name)
I added the changed in the new commit

2023-02-23 13:41 UTC, ygoumaz requested changes
Nice catch for the supervisor! I would just add the `port-argument` as argument when creating the `Ros2SupervisorLauncher` object, so that it is effectively connecting to the correct instance of Webots: https://github.com/cyberbotics/webots_ros2/blob/d5a987829fdcfde7456a41cdfdbb61fffcaac112/webots_ros2_driver/webots_ros2_driver/webots_launcher.py#L67

Finally, you should add the changes to the [changelog](https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2_driver/CHANGELOG.rst) of `webots_ros2_driver` and in the [main changelog](https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2/CHANGELOG.rst) (you can add them under version `2023.0.3`).

2023-02-23 14:39 UTC, omichel requested changes
We try to prefer single quotes to double quotes.

2023-02-23 14:39 UTC, omichel commented on webots_ros2_driver/webots_ros2_driver/utils.py
> +def controller_url_prefix(port="1234"):
```suggestion
def controller_url_prefix(port='1234'):
```

2023-02-23 14:39 UTC, omichel commented on webots_ros2_driver/webots_ros2_driver/webots_launcher.py
> +    def __init__(self, output='screen', respawn=True, port="1234", **kwargs):
```suggestion
    def __init__(self, output='screen', respawn=True, port='1234', **kwargs):
```

2023-02-24 07:51 UTC, ygoumaz requested changes
Thank you. I just have a few minor comments on the changelogs.

2023-02-24 07:51 UTC, ygoumaz commented on webots_ros2_driver/CHANGELOG.rst
> +* Copying .wbproj when launching a webots world via webots_launcher
```suggestion
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023.0.3 (2023-XX-XX)
------------------
* Adding port, stream type parameters to webots_laucher
* Copying .wbproj when launching a webots world via webots_launcher
```

2023-02-24 07:51 UTC, ygoumaz commented on webots_ros2/CHANGELOG.rst
> +* Copying .wbproj when launching a webots world via webots_launcher
This should be moved to a new 2023.0.3 (2023-XX-XX) section.

2023-02-24 11:25 UTC, ygoumaz requested changes
I spotted an additional double quote.

2023-02-24 11:25 UTC, ygoumaz commented on webots_ros2_driver/webots_ros2_driver/webots_launcher.py
> +                 port="1234", **kwargs):
```suggestion
                 port='1234', **kwargs):
```

2023-02-27 09:23 UTC, ygoumaz approved these changes
All good to me now! Thank you!

2023-02-27 10:48 UTC, merged