Replace SLAM toolbox by Cartographer in Tiago
cyberbotics/webots_ros2 pull request #645
Opened 2023-02-28 13:11 UTC by ygoumaz

Resolves #635.

2023-03-01 09:40 UTC, stefaniapedrazzi commented on webots_ros2/CHANGELOG.rst
> +* Replaced Slam-Toolbox by Cartographer in the Tiago example.
Just for info, the correct writing of the robot name is TIAGo.

2023-03-01 15:51 UTC, ad-daniel requested changes
I'm getting this error on foxy:
```
ages/launch/launch_service.py:226> exception=SubstitutionFailure("executable 'cartographer_occupancy_grid_node' not found on the libexec directory '/opt/ros/foxy/lib/cartographer_ros' ")>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 453, in execute
    ret = super().execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 823, in execute
    self.__expand_substitutions(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 668, in __expand_substitutions
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 668, in <listcomp>
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_context.py", line 232, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/substitutions/executable_in_package.py", line 84, in perform
    raise SubstitutionFailure(
launch.substitutions.substitution_failure.SubstitutionFailure: executable 'cartographer_occupancy_grid_node' not found on the libexec directory '/opt/ros/foxy/lib/cartographer_ros' 
[INFO] [rviz2-8]: process started with pid [1741686]
[INFO] [cartographer_node-9]: process started with pid [1741688]

```

2023-03-01 15:53 UTC, ad-daniel commented
![a](https://user-images.githubusercontent.com/44834743/222191967-11745dc3-0aef-4e45-8d27-cca4da248d11.png)

2023-03-02 07:13 UTC, ad-daniel approved these changes
Worked both on humble and foxy (at least what is supported), thank you

2023-03-02 08:33 UTC, merged