get default lidar updateRate from .proto
cyberbotics/webots_ros2 pull request #674
Opened 2023-03-14 21:34 UTC by delihus

**Description**
The default frequency of the lidar sensor is 30Hz when the `updateRate` is not defined in URDF.
This change gets the frequency from the webots lidar device and override default `updateRate`.

**Related Issues**
https://github.com/cyberbotics/webots/pull/5973
**Affected Packages**
List of affected packages:
  - webots_ros2_driver

2023-03-15 07:59 UTC, ygoumaz requested changes
Thank you! Please also update the [main changelog file](https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2/CHANGELOG.rst) and the one in the [webots_ros2_driver](https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2_driver/CHANGELOG.rst) package.

2023-03-15 08:08 UTC, omichel commented on webots_ros2_driver/src/plugins/static/Ros2Lidar.cpp
> +    }
Coding style:
```suggestion
    if (parameters.count("updateRate") == 0)
      parameters.insert({"updateRate", std::to_string(wb_lidar_get_frequency(mLidar))});
```

2023-03-16 08:24 UTC, omichel commented on webots_ros2_driver/src/plugins/static/Ros2Lidar.cpp
> +  {
That should fix the clang-format issue:
```suggestion
namespace webots_ros2_driver {
  void Ros2Lidar::init(webots_ros2_driver::WebotsNode *node, std::unordered_map<std::string, std::string> &parameters) {
```

2023-03-16 08:53 UTC, omichel commented
The tests are now passing.

2023-03-16 09:38 UTC, ygoumaz approved these changes
Thank you!

2023-03-16 09:40 UTC, omichel commented
@delihus, I just sent you an invite to join the GitHub Webots committers group, this will ease your next contributions (no need to fork our repos, merge button enabled, etc.)

2023-03-16 09:40 UTC, merged