Fix emitter receiver nodes
cyberbotics/webots_ros2 pull request #680
Opened 2023-03-22 00:18 UTC by angel-ayala

Changed variables nomenclature for one more standardized and msg new formats.
Update related to #677

2023-03-22 07:44 UTC, omichel commented on webots_ros2_msgs/srv/GetBool.srv
> +bool value
```suggestion
bool value

```

2023-03-22 07:46 UTC, omichel commented
It doesn't compile (see the log of the ROS2 tests / industrial_ci)

2023-03-22 08:13 UTC, ygoumaz requested changes
This PR should only contain the fixes on Emitter and Receiver. The changes about the new Compass plugin should not be contained in this PR.

2023-03-27 16:17 UTC, closed without merging

2023-03-28 08:15 UTC, ygoumaz commented
Emitter and Receiver should still be updated as explained in https://github.com/cyberbotics/webots_ros2/pull/677#issuecomment-1482996502.