Improve TIAGo for better compatibility with real robot
cyberbotics/webots_ros2 pull request #717
Opened 2023-04-24 15:25 UTC by ygoumaz

Resolves #700.

TODO

2023-05-01 08:48 UTC, stefaniapedrazzi commented
All the camera related topics work fine.
But when starting the example all the rest of the topics listed in #700 are still not available, is this correct?

Is this command (from the examples page) still up-to-date?
```ros2 launch webots_ros2_tiago robot_launch.py rviz:=true slam:=true```

In RVIZ I see only the base but not the body nor the map.
![Screenshot from 2023-05-01 10-36-52](https://user-images.githubusercontent.com/5910449/235429830-1d245890-e486-4aa1-a3f5-4480066f4a3c.png)

2023-05-01 09:06 UTC, ygoumaz commented
This command is not up-to-date anymore. I will update it once the PR is merged. To start the full configuration of the TIAGo with all related topics, you should use the following command:

```bash
ros2 launch webots_ros2_tiago robot_bringup_launch.py rviz:=true
```

Note that you can also ignore RViz if you don't want to start it. You also need to install `tiago-bringup` to start all topics:
```bash
sudo apt install ros-humble-tiago-bringup
```

2023-05-01 09:45 UTC, stefaniapedrazzi approved these changes
Thank you!

Now I see that all the topics are available and in RVIZ I can see the full robot in RVIZ.
I still don't have the map and I can no longer move teleoperating the robot as described in the old example but I will wait for the updated example description.

2023-05-01 09:52 UTC, ygoumaz commented
As explained this morning, I have separated both examples. The `robot_launch.py` file is used to start the original example (featuring TIAGo Lite) with SLAM and Navigation. On the other hand, `robot_bringup_launch.py` is used to start the TIAGo with all the topics. Starting everything together is quite a big mess. I think it is clearer to the user if we provide two clear and simple examples and they can always adapt the launch files to add more packages if they need them.

2023-05-01 11:21 UTC, stefaniapedrazzi commented
I will check again once the wiki has been update to see if I missed something, but as I reported previously when starting the old/original launcher, the robot visualization and the SLAM map were not displayed correctly.

2023-05-01 14:01 UTC, stefaniapedrazzi commented
Thank you!
I confirm that all the three examples (navigation, Slam Toolbox, and cartographer) works correctly also for me.

2023-05-01 14:12 UTC, omichel requested changes

2023-05-01 14:12 UTC, omichel commented on webots_ros2_tiago/launch/robot_bringup_launch.py
> +    # The following line is important!
```suggestion
    # The following lines are important!
```

2023-05-01 14:18 UTC, omichel approved these changes
Thank you.

2023-05-01 14:25 UTC, stefaniapedrazzi approved these changes

2023-05-02 07:20 UTC, ygoumaz commented
Tests will run indefinitely until https://github.com/cyberbotics/webots/pull/6113 is merged.

2023-05-03 13:29 UTC, merged