Calculate vertical fov according to https://www.cyberbotics.com/doc/r…
cyberbotics/webots_ros2 pull request #722
Opened 2023-05-02 04:22 UTC by justinberi

…eference/rangefinder

**Description**
 `Ros2RangeFinder::init` uses the incorrectly uses the horizontal field of view to determine the vertical focal length. 
According to https://www.cyberbotics.com/doc/reference/rangefinder the vertical FOV (and thus focal length) should be derived from 
`vertical FOV = 2 * atan(tan(fieldOfView * 0.5) * (height / width))`
This PR implements that change.

PS: Thanks for providing this package! It makes working with sim in ROS2 a easy.

**Affected Packages**
List of affected packages:
  - webots_ros2_driver

**Tasks**
Add the list of tasks of this PR.
  - [x] Implement fix

**Additional context**

Before the fix, point clouds are skewed and do not match the environment.
![before](https://user-images.githubusercontent.com/18635834/235578486-5ec52cb3-e523-4795-b98f-df44e2bf710e.png)

After the fix, point clouds match the environment.
![after](https://user-images.githubusercontent.com/18635834/235578467-db69076c-0f0c-4b8f-b66d-1233a397a04a.png)

2023-05-02 08:11 UTC, ygoumaz requested changes
Thank you for the contribution! Well spotted. I have a few remarks before merging the PR:

- I made some suggestions on the code for clarity.
- You can see that the `test_sources` CI test failed. There is a clang-format error. You can check the logs to see what fails and correct the typo/syntax.
- The changelogs must be updated: [main changelog](https://github.com/justinberi/webots_ros2/blob/fix_rangefinder_point_cloud/webots_ros2/CHANGELOG.rst) and [webots_ros2_driver changelog](https://github.com/justinberi/webots_ros2/blob/fix_rangefinder_point_cloud/webots_ros2_driver/CHANGELOG.rst). You can add an entry for your change under the `2023.0.4` section.

2023-05-02 08:11 UTC, ygoumaz commented on webots_ros2_driver/src/plugins/static/Ros2RangeFinder.cpp
> +    const double focalLengthY = 0.5 * height * (1 / tan(0.5 * vert_fov));
```suggestion
    const double horizontal_fov = wb_range_finder_get_fov(mRangeFinder);
    const double vertical_fov = 2 * atan(tan(horizontal_fov * 0.5) * ( double(height) / width));
    const double focalLengthX = 0.5 * width * (1 / tan(0.5 * horizontal_fov));
    const double focalLengthY = 0.5 * height * (1 / tan(0.5 * vertical_fov));
```

2023-05-03 09:39 UTC, justinberi commented
@ygoumaz thanks for your suggested changes! Also updated the change logs (and some more typos :grin:). Let me know if anything else needs fixing.

2023-05-03 09:41 UTC, ygoumaz requested changes
Just minor suggestions in changelogs and it should be fine!

2023-05-03 09:41 UTC, ygoumaz commented on webots_ros2/CHANGELOG.rst
> +* Fixed vertical field of view in ros2 rangefinder plugin.
```suggestion
* Fixed vertical field of view in static RangeFinder plugin.
```

2023-05-03 09:41 UTC, ygoumaz commented on webots_ros2_driver/CHANGELOG.rst
> +* Fixed vertical field of view in ros2 rangefinder plugin.
```suggestion
* Fixed vertical field of view in static RangeFinder plugin.
```

2023-05-03 09:45 UTC, justinberi commented on webots_ros2_driver/CHANGELOG.rst
> +* Fixed vertical field of view in ros2 rangefinder plugin.
:+1:

2023-05-03 09:47 UTC, ygoumaz approved these changes
Thank you!

2023-05-03 12:30 UTC, merged