Add Ros2Pen static plugin
cyberbotics/webots_ros2 pull request #767
Opened 2023-06-07 13:00 UTC by justinberi

Closes #766

2023-06-09 03:16 UTC, justinberi commented
Thanks. Will do.

2023-06-20 06:39 UTC, ygoumaz requested changes
Thanks a lot for the contribution. Just a very minor last detail and we can merge it.

2023-06-20 06:39 UTC, ygoumaz commented on webots_ros2_msgs/msg/PenInkProperties.msg
> +float32 density
```suggestion
float32 density

```

2023-06-20 06:39 UTC, ygoumaz commented on webots_ros2_msgs/msg/PenInkProperties.msg
> +float32 density
Files should end with an empty line.

2023-06-21 06:46 UTC, ygoumaz approved these changes

2023-06-21 08:06 UTC, ygoumaz commented
Tests fail because no nightly build of Webots is available. They should pass tomorrow.

2023-06-23 14:13 UTC, merged

2023-06-23 20:03 UTC, justinberi commented
Thanks for following up on this!