add remappings to robot state publisher for ur5e example
cyberbotics/webots_ros2 pull request #841
Opened 2023-08-08 13:39 UTC by skpawar1305

follow up to https://github.com/cyberbotics/webots_ros2/commit/f3045ad16c6c41b0edbf845f06391be5d0990022

**Description**
robot state publisher's robot_description update service doesn't get called, and also doesn't subscribe to joint_states' topic, because of the namespace 'ur5e' added to the WebotsController
add remappings to the robot state publisher node to fix it

**Affected Packages**
List of affected packages:
  - webots_ros2_universal_robot

2023-08-08 13:49 UTC, skpawar1305 commented
adding a namespace to the node should've been better, but webotscontroller's service client calls incorrect topic 
'/ur5erobot_state_publisher/set_parameters' instead of '/ur5e/robot_state_publisher/set_parameters'

2023-08-08 14:18 UTC, omichel commented
In that case, I believe we should fix the webots controller service client to call the correct topic.

2023-08-09 08:49 UTC, omichel requested changes
Do you know why the tests are failing on rolling?

2023-08-09 08:49 UTC, omichel commented on webots_ros2_universal_robot/launch/robot_launch/robot_moveit_nodes_launch.py
> +                remappings=[('/joint_states', '/ur5e/joint_states')],
```suggestion
                remappings=[('/joint_states', '/ur5e/joint_states')]
```

2023-08-10 07:31 UTC, skpawar1305 commented
> Do you know why the tests are failing on rolling?

no

2023-08-10 07:33 UTC, omichel approved these changes
I manually restarted the rolling test and it passed.
Probably a random failure or something that was fixed meanwhile.

2023-08-10 13:23 UTC, merged